export {default as Navbar}  from './Navbar/Navbar'
export {default as Hero}  from './Hero/Hero'
export {default as Signup}  from './Signup/SignUp'
export {default as Footer}  from './Footer/Footer'
export {default as Feature}  from './Feature/Feature'